services:
  project-amaan:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: project-amaan-webapp-dev
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=development
      - VITE_APP_URL=http://localhost:9002
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - .env.local